project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Nikolas P. Johnston CPD Level 2 ePortfolio"
  description: "Continuing Professional Development — Learning & Teaching Portfolio"
  favicon: ""
  site-url: "https://nikolasjohnston.github.io/johnston_cpd/"

  navbar:
    background: primary
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: teaching-philosophy.qmd
        text: Teaching Philosophy
      - text: CPD Qualifiers
        menu:
          - href: cpd/cpd1.qmd
            text: "1. Curriculum Design"
          - href: cpd/cpd2.qmd
            text: "2. Inclusive Learning"
          - href: cpd/cpd3.qmd
            text: "3. Learning Pathways"
          - href: cpd/cpd4.qmd
            text: "4. Scaffolded Assessment"
          - href: cpd/cpd5.qmd
            text: "5. Scholarship of T&L"
          - href: cpd/cpd6.qmd
            text: "6. Evaluation & CPD"
          - href: cpd/cpd7.qmd
            text: "7. Professional Practice"
      - href: references.qmd
        text: References

  sidebar:
    - title: "CPD Qualifiers"
      style: "docked"
      background: light
      contents:
        - cpd/cpd1.qmd
        - cpd/cpd2.qmd
        - cpd/cpd3.qmd
        - cpd/cpd4.qmd
        - cpd/cpd5.qmd
        - cpd/cpd6.qmd
        - cpd/cpd7.qmd

  page-footer:
    center: "Dr Nikolas Johnston · School of Chemistry and Molecular Bioscience · University of Wollongong · 2026"


format:
  html:
    theme:
      light: [journal]
      dark: [journal, 'theme-dark.scss']
    code-copy: true
    code-overflow: wrap
    toc: true
freeze: auto

editor: visual

